spring.application.name=bankease
spring.datasource.url=jdbc:postgresql://localhost:5432/bankease
spring.datasource.username=postgres
spring.datasource.password=Aryan1182*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
jwt.secret=[jkbfwvkwjbwvwbhjvkbsjwsbfujibiukjwvbwuvwvjbuwivbjwbjb ]
admin.email=admin@bankease.com
admin.password=AdminPassword123